version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - pwd

  build:
    commands:
      - echo "dev"
      # Set VPCID env variable
  post_build:
    commands:
      - echo Done!