version: 0.2

phases:
  pre_build:
    commands:
      - pwd
      - apt-get install wget -y
      - export OktaMetadataURL=$(aws ssm get-parameters --name OktaMetadataURL --with-decryption --query "Parameters[].Value" --output text)

  build:
    commands:
      - wget -O metadata.xml ${OktaMetadataURL} 
      - cat metadata.xml | tr -d '\n' | sed -e 's/"/\"/g' > out.xml
      - aws cloudformation deploy --no-fail-on-empty-changeset --template-file ./provider.yaml --stack-name OktaProvider --parameter-overrides MetadataDocument="$(cat out.xml)" SamlProviderName=okta --capabilities CAPABILITY_NAMED_IAM
      - aws cloudformation deploy --no-fail-on-empty-changeset --template-file ./okta-user.yaml --stack-name OktaUser --parameter-overrides OktaUsername=okta-master --capabilities CAPABILITY_NAMED_IAM

  post_build:
    commands:
      - echo Done!
