version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - pwd

  build:
    commands:
      - echo "Deploy Standard Okta Roles"
      # Set VPCID env variable
  post_build:
    commands:
      - echo Done!